### ISSUE TITLE
ライブラリがHandshakeを実行したときにサーバー側にエラーが発生する

### ISSUE THREAD

**Issue by Xplove-24** [webiot-c/android_application#15]
https://github.com/webiot-c/raspi_webserver/issues/10 からのものです。
WebSocketのライブラリがHandshakeしようとするとサーバー側でエラーが発生するようです。
必要であれば`miita-handshake-fix`ブランチにて操作します。
### サーバー側のエラーメッセージ(WSLのテスト環境)
```
% sudo python3 server.py
Listening on port 6789 for clients..
----------------------------------------
Exception happened during processing of request from ('(IP of Android)', 47999)
Traceback (most recent call last):File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
  self.finish_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
  self.RequestHandlerClass(request, client_address, self)
File "/usr/local/lib/python3.7/dist-packages/websocket_server/websocket_server.py", line 136, in __init__
  StreamRequestHandler.__init__(self, socket, addr, server)
File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
  self.handle()
File "/usr/local/lib/python3.7/dist-packages/websocket_server/websocket_server.py", line 149, in handle
  self.read_next_message()
File "/usr/local/lib/python3.7/dist-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
ValueError: not enough values to unpack (expected 2, got 0)
----------------------------------------
```

**Comment by Xplove-24** [comment]
調べたら、今この問題についてプルリクが立ってそうな感じがします。
リリースを楽しみに待ちます。

**Comment by Xplove-24** [comment]
サーバー側のライブラリを少し操作することで、応急処置としての対応に成功しました。
一度Closeします。

**Comment by Xplove-24** [comment]
Windowsテスト環境だと問題なかったのですが、ラズパイにてテストしたところ切断されてしまいました！
リリースを楽しみに待ちます。

**Comment by Xplove-24** [comment]
#17 でこの問題は解決したため、これはCloseします。
